apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-app-backend
  namespace: patient-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: patient-app-backend
  template:
    metadata:
      labels:
        app: patient-app-backend
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: patient-app-config
            - secretRef:
                name: {{ .Values.externalSecret.secretName }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
