apiVersion: v1
kind: Service
metadata:
  name: patient-app-backend
  namespace: patient-app
spec:
  selector:
    app: patient-app-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 8000
