{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: patient-app
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: DATABASE_URL
    - secretKey: S3_BUCKET
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: S3_BUCKET
    - secretKey: SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: SECRET_KEY
{{- end }}
