apiVersion: v1
kind: Service
metadata:
  name: patient-app-frontend
  namespace: patient-app
spec:
  selector:
    app: patient-app-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: 8080
