apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-app-frontend
  namespace: patient-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: patient-app-frontend
  template:
    metadata:
      labels:
        app: patient-app-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 8080
