{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: patient-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
            namespace: patient-app
{{- end }}
