apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patient-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ME_OWNER/patient-record-app.git
    targetRevision: HEAD
    path: helm/patient-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: patient-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
