apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- $existing := lookup "v1" "Secret" .Values.namespace "grafana-admin" }}
  {{- if $existing }}
  admin-password: {{ index $existing.data "admin-password" }}
  {{- else }}
  admin-password: {{ randAlphaNum 24 | b64enc }}
  {{- end }}
